name: Vue Storefront
trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - refs/tags/v*

pool:
  vmImage: "ubuntu-latest"

variables:
- group: azure
- group: vsf

jobs:
  - job: build
    displayName: "Build Vue Storefront"
    steps:
      - task: Docker@2
        displayName: Build+Push Docker image
        inputs:
          command: buildAndpush
          Dockerfile: docker/vue-storefront/Dockerfile
          buildContext: $(Build.SourcesDirectory)
          repository: $(DockerRepository)
          containerRegistry: $(AzureContainerRegistry)
          tags: $(DockerTag)-$(Build.SourceBranchName)
