name: Vue Storefront
trigger:
  batch: true
  branches:
    include:
      - master
      - refs/tags/v*

pool:
  vmImage: "ubuntu-latest"

variables:
- group: azure
- group: vsf

jobs:
  - job: build
    displayName: "Build Vue Storefront"
    steps:
      - task: Docker@2
        displayName: Push Docker image
        inputs:
          command: buildAndpush
          Dockerfile: docker/vue-storefront/Dockerfile
          repository: $(DockerRepository)
          containerRegistry: $(AzureContainerRegistry)
          tags: $(DockerTag)
